#!/usr/bin/env python3
"""Crop the downsampled building sprites, compute anchors and write art/buildings_manifest.json.

  buildings_post.py RAW_DIR ATLAS_DIR MANIFEST_JSON SHEET_PNG [--hero HERO_PNG]

Downsamples the raw 2x renders into ATLAS_DIR itself (finish.downsample: premultiplied Lanczos),
then crops them (finish.py's one-row contact sheet would be huge for sprites this size).
* A building and its <name>_shadow share one crop, so one anchorPoint works for both.
* anchor = SpriteKit anchorPoint (origin bottom-left) that puts the CENTRE of the ground
  footprint on the node position. Blender recorded where the world origin landed (origin_1x).
* sign_center_pt / door_pt are already in points relative to the anchor at worldScale 0.3
  (x right, y up), computed in Blender from the 3D positions.
"""
import json, os, sys
from PIL import Image, ImageDraw

WORLD_SCALE = 0.3
PX_PER_UNIT = 256 / 2.2
PAD = 2


def shadow_clean(im, blur=1.5, levels=32):
    """Cycles noise -> smooth: blur the alpha a little and snap it to `levels` steps. Invisible at
    the ~0.4 draw alpha, and the shadow PNGs shrink from ~480 KB to ~20 KB."""
    from PIL import ImageFilter
    q = 256 // levels
    a = im.getchannel("A").filter(ImageFilter.GaussianBlur(blur))
    a = a.point(lambda v: 0 if v < q // 2 else min(255, (v // q) * q + q // 2))
    out = Image.new("RGBA", im.size, (0, 0, 0, 0))
    out.putalpha(a)
    return out


def alpha_box(im):
    return im.getchannel("A").point(lambda a: 255 if a > 3 else 0).getbbox()


def main(argv):
    raw, atlas, manifest_path, sheet_png = argv[:4]
    hero = argv[argv.index("--hero") + 1] if "--hero" in argv else None
    meta = json.load(open(os.path.join(raw, "_meta.json")))
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from finish import downsample
    os.makedirs(atlas, exist_ok=True)
    for n in sorted(os.listdir(raw)):
        if n.endswith(".png"):
            downsample(os.path.join(raw, n), os.path.join(atlas, n), 2)
    out = {}
    for name in sorted(meta):
        m = meta[name]
        cp, sp = os.path.join(atlas, name + ".png"), os.path.join(atlas, name + "_shadow.png")
        if not (os.path.exists(cp) and os.path.exists(sp)):
            continue
        col, sh = Image.open(cp).convert("RGBA"), Image.open(sp).convert("RGBA")
        W, H = col.size
        boxes = [b for b in (alpha_box(col), alpha_box(sh)) if b]
        x0 = max(0, min(b[0] for b in boxes) - PAD); y0 = max(0, min(b[1] for b in boxes) - PAD)
        x1 = min(W, max(b[2] for b in boxes) + PAD); y1 = min(H, max(b[3] for b in boxes) + PAD)
        if (x1 - x0) % 2: x1 = x1 + 1 if x1 < W else x1; x0 = x0 - 1 if (x1 - x0) % 2 else x0
        if (y1 - y0) % 2: y1 = y1 + 1 if y1 < H else y1; y0 = y0 - 1 if (y1 - y0) % 2 else y0
        col.crop((x0, y0, x1, y1)).save(cp, optimize=True)
        shadow_clean(sh.crop((x0, y0, x1, y1))).save(sp, optimize=True)
        cw, ch = x1 - x0, y1 - y0
        ox, oy = m["origin_1x"]
        ax, ay = (ox - x0) / cw, (y1 - oy) / ch
        out[name] = {
            "texture": name,
            "shadow_texture": name + "_shadow",
            "size_px": [cw, ch],
            "size_pt": [round(cw * WORLD_SCALE, 1), round(ch * WORLD_SCALE, 1)],
            "anchor": [round(ax, 4), round(ay, 4)],
            "footprint_pt": m["footprint_pt"],
            "footprint_units": m["footprint_units"],
            "sign_center_pt": m["sign_center_pt"],
            "sign_size_pt": m["sign_size_pt"],
            "door_pt": m["door_pt"],
            "door_top_pt": m["door_top_pt"],
            "door_width_pt": m["door_width_pt"],
        }
        if m.get("variant"):
            out[name]["variant_of"] = m["base"]
        if m.get("note"):
            out[name]["note"] = m["note"]
    man = {
        "_about": ("Generated by art/tools/buildings_post.py - do not edit. Sprites are 1x pixels; "
                   "scale = 0.3 * (spec footprint width / footprint_pt[0]) (uniform). anchor = "
                   "SKSpriteNode.anchorPoint putting the CENTRE of the ground footprint on the node "
                   "position (same anchor for <name>_shadow). footprint_pt = [w, h] of the ground rect "
                   "in world points at scale 0.3 (h = on-screen depth, i.e. foreshortened by cos55 like "
                   "props_manifest). sign_center_pt / door_pt / door_top_pt = offsets in points from the "
                   "node position at scale 0.3 (x right, y up): multiply by (scale / 0.3) for other "
                   "footprints. door_pt is the door threshold (bottom centre, on the front wall line). "
                   "Sign plates are blank light cream: overlay dark text, sized to sign_size_pt. "
                   "Shadows: black RGB, shadow in alpha; tint violet, alpha ~0.4, draw below the building. "
                   "Y-sort by the footprint's front edge (node.y - footprint_h/2), collide with the footprint only."),
        "atlas": "buildings",
        "world_scale": WORLD_SCALE,
        "px_per_unit": round(PX_PER_UNIT, 3),
        "buildings": out,
    }
    json.dump(man, open(manifest_path, "w"), indent=2)
    contact_sheet(atlas, out, sheet_png, hero)
    print(f"[buildings_post] {len(out)} buildings -> {manifest_path}; sheet {sheet_png}")


def contact_sheet(atlas, bl, out, hero=None, max_w=4700, scale=0.5):
    """Buildings over a floor with their violet shadow, footprint rect (white), sign plate rect
    (magenta), door threshold (red dot) and anchor cross; the hero stands at the right front corner
    of every building at the same scale. Saved at `scale` (0.5 -> half size) to keep it light."""
    hero_im = Image.open(hero).convert("RGBA") if hero and os.path.exists(hero) else None
    order = sorted(bl, key=lambda n: (bl[n]["footprint_pt"][0] > 200, n))
    cells = []
    for n in order:
        b = bl[n]
        im = Image.open(os.path.join(atlas, n + ".png")).convert("RGBA")
        sh = Image.open(os.path.join(atlas, b["shadow_texture"] + ".png")).convert("RGBA")
        fw, fh = b["footprint_pt"][0] / 0.3, b["footprint_pt"][1] / 0.3
        cw, ch = im.width + 150, im.height + 40
        c = Image.new("RGBA", (cw, ch), (112, 128, 110, 255))
        px, py = 10, 30
        gx, gy = px + b["anchor"][0] * im.width, py + (1 - b["anchor"][1]) * im.height
        a = sh.getchannel("A").point(lambda v: int(v * 0.4))
        t = Image.new("RGBA", sh.size, (52, 40, 92, 0)); t.putalpha(a)
        c.alpha_composite(t, (px, py))
        d = ImageDraw.Draw(c)
        d.rectangle((gx - fw / 2, gy - fh / 2, gx + fw / 2, gy + fh / 2), outline=(255, 255, 255, 110), width=2)
        c.alpha_composite(im, (px, py))
        d = ImageDraw.Draw(c)
        sx, sy = b["sign_center_pt"]; sw, shh = b["sign_size_pt"]
        d.rectangle((gx + (sx - sw / 2) / 0.3, gy - (sy + shh / 2) / 0.3, gx + (sx + sw / 2) / 0.3,
                     gy - (sy - shh / 2) / 0.3), outline=(255, 0, 200, 255), width=2)
        dx, dy = b["door_pt"]
        d.ellipse((gx + dx / 0.3 - 6, gy - dy / 0.3 - 6, gx + dx / 0.3 + 6, gy - dy / 0.3 + 6), fill=(255, 40, 40, 255))
        d.line((gx - 8, gy, gx + 8, gy), fill=(255, 40, 40, 255), width=2)
        d.line((gx, gy - 8, gx, gy + 8), fill=(255, 40, 40, 255), width=2)
        if hero_im is not None:
            hx, hy = gx + fw / 2 + 10, gy + fh / 2
            c.alpha_composite(hero_im, (int(hx - 0.5 * 256), int(hy - 0.82 * 256)))
        try:
            from PIL import ImageFont
            font = ImageFont.load_default(size=26)
        except Exception:
            font = None
        d.text((8, 2), f"{n}  {b['size_px'][0]}x{b['size_px'][1]}px  fp {b['footprint_pt'][0]}x{b['footprint_pt'][1]}pt",
               fill=(20, 20, 30, 255), font=font)
        cells.append(c)
    rows, row, w = [], [], 0
    for c in cells:
        if row and w + c.width > max_w:
            rows.append(row); row, w = [], 0
        row.append(c); w += c.width
    if row:
        rows.append(row)
    W = max(sum(c.width for c in r) for r in rows)
    H = sum(max(c.height for c in r) for r in rows)
    S = Image.new("RGBA", (W, H), (58, 66, 84, 255))
    y = 0
    for r in rows:
        x = 0; rh = max(c.height for c in r)
        for c in r:
            S.alpha_composite(c, (x, y + rh - c.height)); x += c.width
        y += rh
    if scale != 1:
        S = S.resize((int(W * scale), int(H * scale)), Image.LANCZOS)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    S.convert("RGB").save(out, optimize=True)


if __name__ == "__main__":
    main(sys.argv[1:])
