#!/usr/bin/env python3
"""Crop the downsampled prop sprites, compute SpriteKit anchor points and write the manifest.

  props_post.py RAW_DIR ATLAS_DIR MANIFEST_JSON SHEET_PNG [--hero HERO_PNG]

Run after `finish.py props RAW_DIR ATLAS_DIR ...` has downsampled the 2x renders into ATLAS_DIR.
* A colour sprite and its <name>_shadow share one crop, and every frame of a spin set
  (coin_*, crystal_*) shares one crop, so one anchorPoint works for all of them.
* The anchor is the ground-footprint centre (the world origin of the Blender scene), in SpriteKit
  unit coordinates (origin bottom-left).
* Footprints are in world points at worldScale 0.3: width = units * PX_PER_UNIT * 0.3, height is
  the same but foreshortened by cos(55deg), matching the 70x40pt floor tiles.
"""
import json, math, os, sys
from PIL import Image, ImageDraw

PX_PER_UNIT = 256 / 2.2
WORLD_SCALE = 0.3
FORESHORTEN = math.cos(math.radians(55))
PAD = 2   # px kept around the union bbox


def bbox_union(images):
    box = None
    for im in images:
        b = im.getchannel("A").point(lambda a: 255 if a > 3 else 0).getbbox()
        if b is None:
            continue
        box = b if box is None else (min(box[0], b[0]), min(box[1], b[1]), max(box[2], b[2]), max(box[3], b[3]))
    return box


def main(argv):
    raw, atlas, manifest_path, sheet_png = argv[:4]
    hero = argv[argv.index("--hero") + 1] if "--hero" in argv else None
    meta = json.load(open(os.path.join(raw, "_meta.json")))
    groups = {}
    for name, m in meta.items():
        groups.setdefault(m["group"], []).append(name)

    props = {}
    for g, names in sorted(groups.items()):
        paths = {n: os.path.join(atlas, n + ".png") for n in names}
        ims = {n: Image.open(p).convert("RGBA") for n, p in paths.items() if os.path.exists(p)}
        if not ims:
            continue
        any_m = meta[names[0]]
        W, H = next(iter(ims.values())).size
        ox, oy = W * 0.5, H * (1 - any_m["anchor"])          # origin in image px (y down)
        box = bbox_union(ims.values())
        x0, y0 = max(0, box[0] - PAD), max(0, box[1] - PAD)
        x1, y1 = min(W, box[2] + PAD), min(H, box[3] + PAD)
        # even sizes keep @2x/@3x style scaling tidy
        if (x1 - x0) % 2: x1 = min(W, x1 + 1) if x1 < W else x1; x0 = x0 - 1 if (x1 - x0) % 2 else x0
        if (y1 - y0) % 2: y1 = min(H, y1 + 1) if y1 < H else y1; y0 = y0 - 1 if (y1 - y0) % 2 else y0
        cw, ch = x1 - x0, y1 - y0
        ax = (ox - x0) / cw
        ay = (y1 - oy) / ch
        for n, im in ims.items():
            im.crop((x0, y0, x1, y1)).save(paths[n], optimize=True)
        fw, fd = any_m["footprint_units"]
        colour = sorted(n for n in names if not n.endswith("_shadow"))
        shadow = next((n for n in names if n.endswith("_shadow")), None)
        for n in colour:
            m = meta[n]
            props[n] = {
                "texture": n,
                "shadow_texture": shadow,
                "size_px": [cw, ch],
                "size_pt": [round(cw * WORLD_SCALE, 1), round(ch * WORLD_SCALE, 1)],
                "anchor": [round(ax, 4), round(ay, 4)],
                "footprint_pt": [round(fw * PX_PER_UNIT * WORLD_SCALE, 1),
                                 round(fd * PX_PER_UNIT * WORLD_SCALE * FORESHORTEN, 1)],
                "footprint_depth_pt_unforeshortened": round(fd * PX_PER_UNIT * WORLD_SCALE, 1),
                "footprint_units": [fw, fd],
                "footprint_shape": m["shape"],
                "height_units": m["height_units"],
                "kind": m["kind"],
                "yaw_deg": m["yaw"],
            }
            if m.get("note"):
                props[n]["note"] = m["note"]
            if g != n:
                props[n]["animation"] = g
    # manifest (tiles section is owned by tiles_post.py; keep it)
    man = json.load(open(manifest_path)) if os.path.exists(manifest_path) else {}
    man["_about"] = ("Generated by art/tools/props_post.py and art/tools/tiles_post.py - do not edit. "
                     "Sprites are 1x pixels; use node.setScale(0.3) (SpriteSet.worldScale). "
                     "anchor = SKSpriteNode.anchorPoint putting the ground-footprint centre on the node "
                     "position (use the same anchor for <name>_shadow). footprint_pt = [width, height] "
                     "of the ground footprint in world points at worldScale 0.3, height foreshortened by "
                     "cos55 like the 70x40pt floor tiles (rect centred on the node position). "
                     "Shadows: black RGB, shadow in alpha; tint violet, alpha ~0.4, draw below the prop.")
    man["props_atlas"] = "props"
    man["world_scale"] = WORLD_SCALE
    man["px_per_unit"] = round(PX_PER_UNIT, 3)
    man["props"] = props
    anims = {}
    for n, p in props.items():
        if "animation" in p:
            anims.setdefault(p["animation"], []).append(n)
    man["prop_animations"] = {k: sorted(v, key=lambda s: int(s.rsplit("_", 1)[1])) for k, v in sorted(anims.items())}
    json.dump(man, open(manifest_path, "w"), indent=2)
    contact_sheet(atlas, props, sheet_png, hero)
    print(f"[props_post] {len(props)} props -> {manifest_path}; sheet {sheet_png}")


def contact_sheet(atlas, props, out, hero=None, cols=8):
    """Each prop over a mid-grey-green floor, with its violet shadow and a red anchor cross.
    The hero (if given) is drawn at the same scale in the first cell for size comparison."""
    names = sorted(props, key=lambda n: (props[n].get("animation", n), n))
    cells = []
    if hero and os.path.exists(hero):
        cells.append(("hero (ref)", Image.open(hero).convert("RGBA"), None, (0.5, 0.18), None))
    for n in names:
        p = props[n]
        im = Image.open(os.path.join(atlas, n + ".png")).convert("RGBA")
        sh = Image.open(os.path.join(atlas, p["shadow_texture"] + ".png")).convert("RGBA") if p["shadow_texture"] else None
        cells.append((n, im, sh, p["anchor"], p["footprint_pt"]))
    cw = max(c[1].width for c in cells) + 8
    above = max((1 - c[3][1]) * c[1].height for c in cells)
    below = max(c[3][1] * c[1].height for c in cells)
    chh = int(above + below) + 30
    rows = (len(cells) + cols - 1) // cols
    S = Image.new("RGBA", (cols * cw, rows * chh), (58, 66, 84, 255))
    d = ImageDraw.Draw(S)
    for k, (n, im, sh, anc, fp) in enumerate(cells):
        cx, cy = (k % cols) * cw, (k // cols) * chh
        floor = Image.new("RGBA", (cw - 4, chh - 20), (112, 128, 110, 255))
        # common ground line shared by every cell
        gx, gy = floor.width // 2, int(above) + 4
        px, py = int(gx - anc[0] * im.width), int(gy - (1 - anc[1]) * im.height)
        if sh is not None:
            a = sh.getchannel("A").point(lambda v: int(v * 0.4))
            tint = Image.new("RGBA", sh.size, (52, 40, 92, 0)); tint.putalpha(a)
            floor.alpha_composite(tint, (px, py))
        if fp:
            fw, fh = fp[0] / 0.3, fp[1] / 0.3
            ImageDraw.Draw(floor).rectangle((gx - fw / 2, gy - fh / 2, gx + fw / 2, gy + fh / 2), outline=(255, 255, 255, 90))
        floor.alpha_composite(im, (px, py))
        fd = ImageDraw.Draw(floor)
        fd.line((gx - 4, gy, gx + 4, gy), fill=(255, 40, 40, 255)); fd.line((gx, gy - 4, gx, gy + 4), fill=(255, 40, 40, 255))
        S.alpha_composite(floor, (cx + 2, cy + 18))
        d.text((cx + 4, cy + 4), n, fill=(235, 235, 240, 255))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    S.convert("RGB").save(out, optimize=True)


if __name__ == "__main__":
    main(sys.argv[1:])
